#sample imperative command is transfered into the declarative command 
#kubectl expose deployment first-app --type=LoadBalancer --port=8080
apiVersion: v1
kind: Service
metadata: 
  name: backend-serice
  labels:
    group: example
spec:
  selector:
    app: first-app
    tier: backend # no need to specify the all the labels in many times
  ports:
    - protocol: 'TCP'
      port: 80 # to access the application outside of the application 
      targetPort: 8080 # inside the container port means declare into the node js application

      # At the same time we define multiple port in the same conatier to access thr app outside the world
      #
  type: LoadBalancer #CluserIP -> which is default ip which is expose the port Internally to the cluster
  # NodePort -> Which is expose the port and ip at the worker node 
  # LoadBalancer -> access outside the world means the pods expose the outside the world and also distribute the request equally 
