apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: host-pvc
spec:
  volumeName: host-pv #mention the name of volumen which volume we wanna use
  resources:
    requests:
      storage: 1Gi # for
  storageClassName: standard 
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
